// client-vue/src/views/Blog.vue
<template>
  <div class="columns">
    <div class="column is-two-thirds" data-test="blog">
      <div class="content">
        <h1 class="title">Vue Blog</h1>

        <ul>
          <li v-for="post in posts" :key="post.id">
            <router-link :to="`/posts/${post.id}`">{{
              post.title
            }}</router-link>
            by
            <router-link :to="`/users/${post.author.id}`">{{
              post.author.name
            }}</router-link>
          </li>
        </ul>
      </div>
    </div>

    <div class="column is-one-third">
      <h1 class="title">New Post</h1>
      <blog-post-form @submit:post="createPost" />
    </div>
  </div>
</template>

<script>
import BlogPostForm from '@/components/BlogPostForm.vue'

export default {
  name: 'blog',

  components: {
    BlogPostForm,
  },

  mounted() {
    this.$store.dispatch('fetchAllPosts')
  },

  computed: {
    posts() {
      return this.$store.state.posts || []
    },
  },

  methods: {
    createPost(post) {
      this.$store.dispatch('createPost', post)
    },
  },
}
</script>

<style></style>

// client-angular/src/app/blog-posts/blog/blog.component.ts
import { Component, OnInit } from '@angular/core'
import { BlogPost } from '../blog-post'
import { BlogPostService } from '../blog-posts.service'

@Component({
  selector: 'blog',
  templateUrl: './blog.component.html',
  styleUrls: [],
})
export class BlogComponent implements OnInit {
  posts: Array<BlogPost> = []

  constructor(private postService: BlogPostService) {}

  ngOnInit(): void {
    this.postService.getUsers().then((posts) => {
      this.posts = posts
    })
  }
}

<div class="columns">
  <div class="column is-two-thirds" data-test="blog">
    <div class="content">
      <h1 class="title">Angular Blog</h1>

      <ul>
        <li *ngFor="let post of posts">
          <a [routerLink]="['/posts/', post.id]">{{ post.title }}</a>
          by
          <a [routerLink]="['/users/', post.author.id]">{{ post.author.name }}</a>
        </li>
      </ul>
    </div>
  </div>

  <div class="column is-one-third">
    <h1 class="title">New Post</h1>
    TODO: BlogPostForm
    <!-- <blog-post-form (submitEvent)="createPost($event)" /> -->
  </div>
</div>
