// vue-client/src/components/NavBar.vue
<template>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="container">
      <div class="navbar-brand">
        <a
          role="button"
          class="navbar-burger"
          aria-label="menu"
          aria-expanded="false"
        >
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div class="navbar-menu">
        <div class="navbar-start">
          <router-link class="navbar-item" to="/blog">Blog</router-link>
          <router-link class="navbar-item" to="/authors">Authors</router-link>
          <!-- <router-link class="navbar-item" to="/">Home</router-link>
          <router-link class="navbar-item" to="/about">About</router-link> -->
        </div>
        <div class="navbar-end">
          <user-select></user-select>
        </div>
      </div>
    </div>
  </nav>
</template>

<script>
import UserSelect from '@/components/UserSelect.vue'
export default {
  name: 'nav-bar',

  components: {
    UserSelect,
  },
}
</script>

<style></style>

// client-react/src/components/NavBar.js
import { Component } from 'react'
import { Link } from 'react-router-dom'

export default class NavBar extends Component {
  render() {
    return (
      <nav className="navbar" role="navigation" aria-label="main navigation">
        <div className="container">
          <div className="navbar-brand">
            <button
              className="navbar-burger"
              aria-label="menu"
              aria-expanded="false"
            >
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </button>
          </div>

          <div className="navbar-menu">
            <div className="navbar-start">
              <Link className="navbar-item" to="/">
                Blog
              </Link>
              <Link className="navbar-item" to="/authors">
                Authors
              </Link>
            </div>
            <div className="navbar-end">TODO: UserSelect</div>
          </div>
        </div>
      </nav>
    )
  }
}
