// client-vue/src/views/UserList.vue
<template>
  <div class="columns">
    <div class="column is-two-thirds">
      <div class="content">
        <h1 class="title">Users</h1>

        <ul data-test="user-list">
          <li v-for="user in users" :key="user.id">
            <router-link :to="`/users/${user.id}`">{{ user.name }}</router-link>
            {{ authorText(user) }}
          </li>
        </ul>
      </div>
    </div>
    <div class="column is-one-third">
      <h1 class="title">New User</h1>

      <user-form @submit:user="createUser" />
    </div>
  </div>
</template>

<script>
import UserForm from '@/components/UserForm.vue'

export default {
  name: 'users',

  components: {
    UserForm,
  },

  mounted() {
    this.$store.dispatch('fetchAllUsers')
  },

  computed: {
    users() {
      return this.$store.state.users || []
    },
  },

  methods: {
    createUser(user) {
      this.$store.dispatch('createUser', user)
    },

    authorText(user) {
      return user.posts.length > 0 ? '(author)' : ''
    },
  },
}
</script>

<style></style>

// client-react/src/views/UserList.js
import { useSelector, useDispatch } from 'react-redux'
import { Link } from 'react-router-dom'

import { UserForm, LoadingData } from '../components'
import {
  selectUsers,
  createUser,
  selectStatus,
} from '../store/users/users.slice'

export default function UserList() {
  const users = useSelector(selectUsers)
  const status = useSelector(selectStatus)
  const dispatch = useDispatch()

  let userList = null
  if (status === 'loading') {
    userList = <LoadingData />
  } else {
    userList = users.map((user) => (
      <li key={user.id}>
        <Link to={`/users/${user.id}`}>{user.name}</Link>{' '}
        {user.posts.length > 0 ? '(author)' : ''}
      </li>
    ))
  }

  return (
    <div className="columns">
      <div className="column is-two-thirds">
        <div className="content">
          <h1 className="title">Users</h1>

          <ul data-test="user-list">{userList}</ul>
        </div>
      </div>
      <div className="column is-one-third">
        <h1 className="title">New User</h1>

        <UserForm onSubmit={(user) => dispatch(createUser(user))} />
      </div>
    </div>
  )
}
