// client-vue/src/views/User.vue
<template>
  <div v-if="loaded && exists">
    <div v-if="inReadMode" class="content">
      <h1 class="title">{{ user.name }}</h1>

      <div class="buttons">
        <button class="button" @click="edit = true">Edit</button>
        <button class="button is-danger is-outlined" @click="deleteUser">
          Delete
        </button>
      </div>

      <h2 class="subtitle is-4">Posts</h2>
      <ul>
        <li v-for="post in user.posts" :key="post.id">
          <router-link :to="`/posts/${post.id}`">{{ post.title }}</router-link>
        </li>
      </ul>
    </div>
    <div v-else>
      <h1 class="title">Edit User</h1>

      <user-form
        :populateWith="user"
        @submit:user="editUser"
        @close="edit = false"
      />
    </div>
  </div>
  <div v-else-if="loaded && !exists">
    <h1 class="title">404</h1>
    User not found
  </div>
  <div v-else>
    <p>Loading data...</p>
    <progress class="progress is-primary" max="100">70%</progress>
  </div>
</template>

<script>
import UserForm from '@/components/UserForm.vue'

export default {
  name: 'user',

  components: {
    UserForm,
  },

  data() {
    return {
      edit: false,
      loaded: false,
      exists: true,
      user: {},
    }
  },

  async mounted() {
    const userId = this.$route.params.id
    this.$store
      .dispatch('fetchOneUser', userId)
      .then(() => {
        this.setUser(this.$store.getters.getUserById(userId))
      })
      .catch((err) => {
        console.log(`fetch user with id ${userId} failed, error = `, err)
        this.setUser(null)
      })
  },

  computed: {
    inReadMode() {
      return !this.edit
    },

    inEditMode() {
      return this.edit
    },
  },

  methods: {
    setUser(user) {
      this.loaded = true
      if (user == null) {
        this.exists = false
      } else {
        this.user = user
      }
    },

    editUser(user) {
      console.log('submitting edited user !')
      this.$store.dispatch('editUser', user).then(() => {
        console.log('submitted edited user !')
        this.user = this.$store.getters.getUserById(this.user.id)
      })
    },

    deleteUser() {
      if (confirm('Are you sure you want to delete this user?')) {
        this.$store.dispatch('deleteUser', this.user.id).then(() => {
          this.$router.push('/authors')
        })
      }
    },
  },
}
</script>

<style></style>

// client-react/src/views/User.js
import { Component } from 'react'
import { Link, withRouter } from 'react-router-dom'
import { UserForm } from '../components'
import http from '../http-common'

class User extends Component {
  constructor(props) {
    super(props)

    this.state = {
      edit: false,
      loaded: false,
      exists: true,
      user: {},
    }

    this.editUser = this.editUser.bind(this)
    this.deleteUser = this.deleteUser.bind(this)
  }

  componentDidMount() {
    const id = this.props.match.params.id
    http
      .get(`/users/${id}`)
      .then(({ data }) => {
        this.setState({
          user: data,
          loaded: true,
          exists: true,
        })
      })
      .catch((err) => {
        console.log(`fetch user with id ${id} failed, error = `, err)
        this.setState({
          loaded: true,
          exists: false,
        })
      })
  }

  unloadedRender() {
    return (
      <div>
        <p>Loading data...</p>
        <progress className="progress is-primary" max="100">
          70%
        </progress>
      </div>
    )
  }

  notFoundRender() {
    return (
      <div>
        <h1 className="title">404</h1>
        User not found
      </div>
    )
  }

  readModeRender() {
    const posts = this.state.user.posts.map((post) => (
      <li key={post.id}>
        <Link to={`/posts/${post.id}`}>{post.title}</Link>
      </li>
    ))

    return (
      <div className="content">
        <h1 className="title">{this.state.user.name}</h1>

        <div className="buttons">
          <button
            className="button"
            onClick={() => {
              this.setState({ edit: true })
            }}
          >
            Edit
          </button>
          <button
            className="button is-danger is-outlined"
            onClick={this.deleteUser}
          >
            Delete
          </button>
        </div>

        <h2 className="subtitle is-4">Posts</h2>
        <ul>{posts}</ul>
      </div>
    )
  }

  editModeRender() {
    return (
      <div>
        <h1 className="title">Edit User</h1>
        <UserForm
          populateWith={this.state.user}
          onSubmit={this.editUser}
          onClose={() => this.setState({ edit: false })}
        />
      </div>
    )
  }

  render() {
    if (!this.state.loaded) {
      return this.unloadedRender()
    } else if (this.state.loaded && !this.state.exists) {
      return this.notFoundRender()
    } else if (this.state.edit) {
      return this.editModeRender()
    } else {
      return this.readModeRender()
    }
  }

  editUser(editedName) {
    const id = this.state.user.id
    http
      .patch(`/users/${id}`, { name: editedName })
      .then(({ data }) => {
        this.setState({ user: data })
      })
      .catch((err) => {
        console.log(`API error when updating user with id ${id}:`, err)
      })
  }

  deleteUser() {
    if (window.confirm('Are you sure you want to delete this user?')) {
      const id = this.state.user.id
      http
        .delete(`/users/${this.state.user.id}`)
        .then(() => {
          this.props.history.push('/users')
        })
        .catch((err) => {
          console.log(`API error when deleting user with id ${id}:`, err)
        })
    }
  }
}

export default withRouter(User)
