// client-react/src/views/Blog.js
import { useSelector, useDispatch } from 'react-redux'
import { Link } from 'react-router-dom'
import { BlogPostForm, LoadingData } from '../components'

import {
  selectPosts,
  createPost,
  selectStatus,
} from '../store/posts/posts.slice'

export default function Blog() {
  const posts = useSelector(selectPosts)
  const status = useSelector(selectStatus)
  const dispatch = useDispatch()

  let blogPosts
  if (status === 'loading') {
    blogPosts = <LoadingData />
  } else {
    blogPosts = posts.map((post) => (
      <li key={post.id}>
        <Link to={`/posts/${post.id}`}>{post.title}</Link> by{' '}
        <Link to={`/users/${post.userId}`}>{post.author.name}</Link>
      </li>
    ))
  }

  return (
    <div className="columns">
      <div className="column is-two-thirds" data-test="blog">
        <div className="content">
          <h1 className="title">React Blog</h1>

          <ul>{blogPosts}</ul>
        </div>
      </div>

      <div className="column is-one-third">
        <h1 className="title">New Post</h1>
        <BlogPostForm onSubmit={(post) => dispatch(createPost(post))} />
      </div>
    </div>
  )
}

// client-vue/src/views/Blog.vue
<template>
  <div class="columns">
    <div class="column is-two-thirds" data-test="blog">
      <div class="content">
        <h1 class="title">Vue Blog</h1>

        <ul>
          <li v-for="post in posts" :key="post.id">
            <router-link :to="`/posts/${post.id}`">{{
              post.title
            }}</router-link>
            by
            <router-link :to="`/users/${post.author.id}`">{{
              post.author.name
            }}</router-link>
          </li>
        </ul>
      </div>
    </div>

    <div class="column is-one-third">
      <h1 class="title">New Post</h1>
      <blog-post-form @submit:post="createPost" />
    </div>
  </div>
</template>

<script>
import BlogPostForm from '@/components/BlogPostForm.vue'

export default {
  name: 'blog',

  components: {
    BlogPostForm,
  },

  mounted() {
    this.$store.dispatch('fetchAllPosts')
  },

  computed: {
    posts() {
      return this.$store.state.posts || []
    },
  },

  methods: {
    createPost(post) {
      this.$store.dispatch('createPost', post)
    },
  },
}
</script>

<style></style>
