// client-angular/src/app/users/user/user.component.ts
import { Component, OnInit } from '@angular/core'
import { User } from '../user'
import { UsersService } from '../users.service'
import { ActivatedRoute, Router } from '@angular/router'

@Component({
  selector: 'user',
  templateUrl: './user.component.html',
  styleUrls: [],
})
export class UserComponent implements OnInit {
  inEditMode = false
  loaded = false
  exists = true
  user: User = {
    id: null,
    name: '',
    posts: [],
  }

  constructor(
    private userService: UsersService,
    private route: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe((params) => {
      const id = parseInt(params['id'])
      this.fetchUser(id)
    })
  }

  fetchUser(id: number) {
    this.userService
      .getUserById(id)
      .then((user) => {
        this.user = user
        this.loaded = true
        this.exists = true
      })
      .catch((_err) => {
        this.loaded = true
        this.exists = false
      })
  }

  setEditMode(value: boolean): void {
    this.inEditMode = value
  }

  editUser(editedUser: User): void {
    this.userService.updateUser(editedUser).then((_user) => {
      if (this.user.id) this.fetchUser(this.user.id)
    })
  }

  deleteUser(): void {
    if (confirm('Are you sure you want to delete this user?')) {
      this.userService.deleteUser(this.user)
      this.router.navigate(['/users'])
    }
  }
}

<loading-data *ngIf="!loaded"></loading-data>
<entry-not-found *ngIf="loaded && !exists" :type="User"></entry-not-found>
<div *ngIf="loaded && exists">
  <div *ngIf="!inEditMode" class="content">
    <h1 class="title">{{ user.name }}</h1>

    <div class="buttons">
      <button class="button" (click)="setEditMode(true)">Edit</button>
      <button class="button is-danger is-outlined" (click)="deleteUser()">
        Delete
      </button>
    </div>

    <h2 class="subtitle is-4">Posts</h2>
    <ul>
      <li *ngFor="let post of user.posts">
        <a [routerLink]="['/posts/', post.id]">{{ post.title }}</a>
      </li>
    </ul>
  </div>

  <div *ngIf="inEditMode">
    <h1 class="title">Edit User</h1>
    <user-form
      [populateWith]="user"
      (submitEvent)="editUser($event)"
      (closeEvent)="setEditMode(false)">
    </user-form>
  </div>
</div>

// client-vue/src/views/User.vue
<template>
  <div v-if="loaded && exists">
    <div v-if="inReadMode" class="content">
      <h1 class="title">{{ user.name }}</h1>

      <div class="buttons">
        <button class="button" @click="edit = true">Edit</button>
        <button class="button is-danger is-outlined" @click="deleteUser">
          Delete
        </button>
      </div>

      <h2 class="subtitle is-4">Posts</h2>
      <ul>
        <li v-for="post in user.posts" :key="post.id">
          <router-link :to="`/posts/${post.id}`">{{ post.title }}</router-link>
        </li>
      </ul>
    </div>
    <div v-else>
      <h1 class="title">Edit User</h1>

      <user-form
        :populateWith="user"
        @submit:user="editUser"
        @close="edit = false"
      />
    </div>
  </div>
  <div v-else-if="loaded && !exists">
    <h1 class="title">404</h1>
    User not found
  </div>
  <div v-else>
    <p>Loading data...</p>
    <progress class="progress is-primary" max="100">70%</progress>
  </div>
</template>

<script>
import UserForm from '@/components/UserForm.vue'

export default {
  name: 'user',

  components: {
    UserForm,
  },

  data() {
    return {
      edit: false,
      loaded: false,
      exists: true,
      user: {},
    }
  },

  async mounted() {
    const userId = this.$route.params.id
    this.$store
      .dispatch('fetchOneUser', userId)
      .then(() => {
        this.setUser(this.$store.getters.getUserById(userId))
      })
      .catch((err) => {
        console.log(`fetch user with id ${userId} failed, error = `, err)
        this.setUser(null)
      })
  },

  computed: {
    inReadMode() {
      return !this.edit
    },

    inEditMode() {
      return this.edit
    },
  },

  methods: {
    setUser(user) {
      this.loaded = true
      if (user == null) {
        this.exists = false
      } else {
        this.user = user
      }
    },

    editUser(user) {
      console.log('submitting edited user !')
      this.$store.dispatch('editUser', user).then(() => {
        console.log('submitted edited user !')
        this.user = this.$store.getters.getUserById(this.user.id)
      })
    },

    deleteUser() {
      if (confirm('Are you sure you want to delete this user?')) {
        this.$store.dispatch('deleteUser', this.user.id).then(() => {
          this.$router.push('/authors')
        })
      }
    },
  },
}
</script>

<style></style>
