// client-react/src/components/BlogPostForm.js
import { Component } from 'react'
const _pick = require('lodash.pick')

export default class BlogPostForm extends Component {
  constructor(props) {
    super(props)

    this.state = {
      edit: false,
      submitting: false,
      error: false,
      success: false,
      post: {
        userId: null,
        id: null,
        title: '',
        content: '',
      },
    }

    this.handleInputChange = this.handleInputChange.bind(this)
    this.handleSubmit = this.handleSubmit.bind(this)
    this.close = this.close.bind(this)
  }

  componentDidMount() {
    if (this.props.populateWith) {
      this.setState({
        post: { ...this.props.populateWith },
        edit: true,
      })
    }
  }

  clearStatus() {
    this.setState({
      success: false,
      error: false,
    })
  }

  clearForm() {
    this.setState({
      edit: false,
      post: {
        userId: null,
        id: null,
        title: '',
        content: '',
      },
    })
  }

  handleSubmit(event) {
    event.preventDefault()

    this.setState({ submitting: true })
    this.clearStatus()

    if (!this.state.edit) {
      // TODO: Get 'logged in' user from store
      const post = { ...this.state.post }
      post.userId = 1
      this.setState({ post })
    }
    if (
      !this.state.post.title ||
      !this.state.post.content ||
      !this.state.post.userId
    ) {
      this.setState({ error: true })
      return
    }

    this.props.onSubmit(_pick(this.state.post, ['title', 'content', 'userId']))
    this.clearForm()
    this.setState({
      error: false,
      success: true,
      submitting: false,
    })
    this.close()
  }

  close(event) {
    event?.preventDefault?.()
    this.props.onClose?.()
  }

  handleInputChange(event) {
    const target = event.target

    const post = { ...this.state.post }
    post[target.name] = target.value
    this.setState({
      post,
    })
  }

  render() {
    return (
      <form id="blog-post-form" onSubmit={this.handleSubmit}>
        <div className="field">
          <label className="label">Title</label>
          <div className="control">
            <input
              className={`input ${
                this.state.submitting && !this.state.post.title
                  ? 'is-danger'
                  : ''
              }`}
              type="text"
              placeholder="Post Title"
              name="title"
              value={this.state.post.title}
              onChange={this.handleInputChange}
            />
          </div>
          {this.state.submitting && !this.state.post.title && (
            <p className="help is-danger">Title cannot be empty</p>
          )}
        </div>

        <div className="field">
          <label className="label">Content</label>
          <div className="control">
            <textarea
              className={`textarea ${
                this.state.submitting && !this.state.post.content
                  ? 'is-danger'
                  : ''
              }`}
              placeholder="Post Content"
              name="content"
              value={this.state.post.content}
              onChange={this.handleInputChange}
            ></textarea>
          </div>
          {this.state.submitting && !this.state.post.content && (
            <p className="help is-danger">Content cannot be empty</p>
          )}
        </div>

        {this.state.submitting && !this.state.error && (
          <div className="field">
            <p v-if="error && submitting" className="help is-danger">
              You need to be "logged in" as a user to add a post
            </p>
          </div>
        )}

        <div className="field is-grouped">
          <div className="control">
            <button type="submit" className="button is-primary">
              {this.state.edit ? 'Edit' : 'Create'}
            </button>
          </div>

          {this.state.edit && (
            <div className="control">
              <button
                className="button is-danger is-outlined"
                onClick={this.close}
              >
                Cancel
              </button>
            </div>
          )}
        </div>
      </form>
    )
  }
}

// client-vue/src/components/BlogPostForm.vue
<template>
  <form id="blog-post-form" @submit.prevent="onSubmit">
    <div class="field">
      <label class="label">Title</label>
      <div class="control">
        <input
          class="input"
          :class="{ 'is-danger': submitting && invalidTitle }"
          type="text"
          placeholder="Post Title"
          v-model="post.title"
        />
      </div>
      <p v-if="submitting && invalidTitle" class="help is-danger">
        Title cannot be empty
      </p>
    </div>

    <div class="field">
      <label class="label">Content</label>
      <div class="control">
        <textarea
          class="textarea"
          :class="{ 'is-danger': submitting && invalidContent }"
          placeholder="Post Content"
          v-model="post.content"
        ></textarea>
      </div>
      <p v-if="submitting && invalidContent" class="help is-danger">
        Content cannot be empty
      </p>
    </div>

    <div class="field">
      <p v-if="error && submitting" class="help is-danger">
        You need to be "logged in" as a user to add a post
      </p>
    </div>

    <div class="field is-grouped">
      <div class="control">
        <button type="submit" class="button is-primary">
          {{ submitText }}
        </button>
      </div>

      <div class="control">
        <button
          v-if="inEditMode"
          class="button is-danger is-outlined"
          @click="close"
        >
          Cancel
        </button>
      </div>
    </div>
  </form>
</template>

<script>
export default {
  name: 'blog-post-form',
  props: {
    populateWith: {
      type: Object,
      default: () => ({ empty: true }),
    },
  },

  data() {
    return {
      edit: false,
      submitting: false,
      error: false,
      success: false,
      post: {
        userId: null,
        id: null,
        title: '',
        content: '',
      },
    }
  },

  created() {
    if (!this.populateWith.empty) {
      this.post = { ...this.populateWith }
      this.edit = true
    }
  },

  computed: {
    inCreationMode() {
      return !this.edit
    },

    inEditMode() {
      return this.edit
    },

    submitText() {
      return this.inCreationMode ? 'Create' : 'Edit'
    },

    invalidTitle() {
      return this.post.title === ''
    },

    invalidContent() {
      return this.post.content === ''
    },

    invalidPostAuthor() {
      return !this.post.userId
    },
  },

  methods: {
    onSubmit() {
      this.submitting = true
      this.clearStatus()

      if (this.inCreationMode) {
        this.post.userId = this.$store.getters.getCurentUserId
      }
      if (this.invalidTitle || this.invalidContent || this.invalidPostAuthor) {
        this.error = true
        return
      }

      this.$emit('submit:post', this.post)
      this.clearForm()
      this.error = false
      this.success = true
      this.submitting = false
      this.close()
    },

    clearStatus() {
      this.success = false
      this.error = false
    },

    clearForm() {
      this.post = {
        userId: null,
        id: null,
        title: '',
        content: '',
      }
      this.edit = false
    },

    close() {
      this.$emit('close')
    },
  },
}
</script>

<style></style>
