// client-react/src/components/UserSelect.js
import { useState } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import {
  selectCurrentUser,
  setCurrentUser,
  selectUsers,
} from '../store/users/users.slice'

export default function UserSelect() {
  const users = useSelector(selectUsers)
  const currentUser = useSelector(selectCurrentUser)
  const dispatch = useDispatch()

  const emptyOption = ''
  const defaultSelectValue = currentUser
    ? toString(currentUser.id)
    : emptyOption
  const [selectValue, editSelectValue] = useState(defaultSelectValue)

  const handleChange = (event) => {
    const value = event.target.value
    const id = parseInt(value)
    const user = users.find((u) => u.id === id)
    if (user) {
      dispatch(setCurrentUser(user))
      editSelectValue(value)
    } else {
      dispatch(setCurrentUser(null))
      editSelectValue(emptyOption)
    }
  }

  // add an empty default option
  const usersOptions = [{ id: emptyOption, name: '' }, ...users]
  const options = usersOptions.map((user) => (
    <option value={user.id} key={user.id}>
      {user.name}
    </option>
  ))
  return (
    <div data-test="user-select" className="columns">
      <div className="column">
        <div className="navbar-item">I am :</div>
      </div>
      <div className="column">
        <div className="select">
          <select value={selectValue} onChange={handleChange}>
            {options}
          </select>
        </div>
      </div>
    </div>
  )
}

// client-vue/src/components/UserSelect.vue
<template>
  <div data-test="user-select" class="columns">
    <div class="column">
      <div class="navbar-item">I am :</div>
    </div>
    <div class="column">
      <div class="select">
        <select v-model="currentUser">
          <option v-for="user in users" :value="user" :key="user.id">
            {{ user.name }}
          </option>
        </select>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'user-select',

  mounted() {
    this.$store.dispatch('fetchAllUsers')
  },

  computed: {
    users() {
      return this.$store.state.users
    },

    currentUser: {
      get() {
        return this.$store.state.currentUser
      },

      set(value) {
        this.$store.commit('setCurrentUser', value)
      },
    },
  },
}
</script>

<style></style>
