// client-angular/src/app/users/user-form/user-form.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core'
import {
  FormControl,
  Validators,
  ValidatorFn,
  AsyncValidatorFn,
  AbstractControl,
  ValidationErrors,
} from '@angular/forms'
import { User } from '../user'
import { UsersService } from '../users.service'

@Component({
  selector: 'user-form',
  templateUrl: './user-form.component.html',
  styleUrls: [],
})
export class UserFormComponent implements OnInit {
  @Input() populateWith?: User

  @Output() closeEvent = new EventEmitter<void>()
  @Output() submitEvent = new EventEmitter<User>()

  username = new FormControl('', {
    validators: [Validators.required, this.differentUsername()],
    asyncValidators: this.availableUsername(),
    updateOn: 'change',
  })

  user: User = {
    id: null,
    name: '',
    posts: [],
  }

  editingExistingUser = false

  constructor(private userService: UsersService) {}

  ngOnInit(): void {
    if (this.populateWith) {
      this.user = { ...this.populateWith }
      this.username.setValue(this.populateWith.name)
      this.editingExistingUser = true
    }
  }

  differentUsername(): ValidatorFn {
    return (control: AbstractControl): ValidationErrors | null => {
      return control.value === this.populateWith?.name
        ? { currentUsername: { value: control.value } }
        : null
    }
  }

  availableUsername(): AsyncValidatorFn {
    return (control: AbstractControl): Promise<ValidationErrors | null> => {
      const unavailable = { unavailable: { value: control.value } }
      return this.userService
        .getAvailabilty(control.value)
        .then((available: boolean) => {
          return !available ? unavailable : null
        })
        .catch(() => {
          return unavailable
        })
    }
  }

  submitText(): string {
    return this.editingExistingUser ? 'Edit' : 'Create'
  }

  clearForm(): void {
    this.user = {
      id: null,
      name: '',
      posts: [],
    }
    this.editingExistingUser = false
    this.username.setValue(this.user.name)
  }

  close(): void {
    this.closeEvent.emit()
  }

  onSubmit(): void {
    this.submitEvent.emit({ ...this.user, name: this.username.value })
    this.clearForm()
    this.username.reset()
    this.close()
  }
}

<form data-test="user-form" (ngSubmit)="onSubmit()">
  <div class="field">
    <label class="label">Name</label>
    <div class="control">
      <input
        class="input"
        type="text"
        name="username"
        data-test="username-field"
        placeholder="John Doe"
        [class.is-danger]="username.dirty && username.invalid"
        [formControl]="username"
        />

    </div>
    <div *ngIf="username.dirty">
      <p *ngIf="username.errors?.required" class="help is-danger">User name cannot be empty</p>
      <p *ngIf="username.errors?.currentUsername" class="help is-danger">This is the current username</p>
      <p *ngIf="username.errors?.unavailable" class="help is-danger">This username is not available</p>

      <p *ngIf="username.valid" class="help is-success">This username is available</p>
    </div>
  </div>

  <div class="buttons">
    <button
      class="button is-primary"
      type="submit"
      [disabled]="!username.valid"
    >
    {{ submitText() }}
    </button>

    <button *ngIf="editingExistingUser" class="button is-danger is-outlined" type="button" (click)="close()">
      Cancel
    </button>
  </div>
</form>

// client-vue/src/components/UserForm.vue
<template>
  <form data-test="user-form" @submit.prevent="onSubmit">
    <div class="field">
      <label class="label">Name</label>
      <div class="control">
        <input
          class="input"
          type="text"
          data-test="username-field"
          placeholder="John Doe"
          v-model="username"
        />
      </div>
      <p v-if="nameIsEmpty" class="help is-danger">User name cannot be empty</p>
      <p v-else-if="inputIsCurrentUsername" class="help is-danger">
        This is the current username
      </p>
      <p v-else-if="!usernameAvailable" class="help is-danger">
        This username is not available
      </p>
      <p v-else class="help is-success">This username is available</p>
    </div>

    <div class="buttons">
      <button
        type="submit"
        class="button is-primary"
        :disabled="!canSubmit ? '' : false"
      >
        {{ submitText }}
      </button>
      <button
        v-if="inEditMode"
        class="button is-danger is-outlined"
        @click="close"
      >
        Cancel
      </button>
    </div>
  </form>
</template>

<script>
import http from '../http-common'

export default {
  name: 'user-form',
  props: {
    populateWith: {
      type: Object,
      default: () => ({ empty: true }),
    },
  },

  data() {
    return {
      edit: false,
      usernameAvailable: true,
      user: {
        id: null,
        name: '',
        posts: [],
      },
    }
  },

  created() {
    if (!this.populateWith.empty) {
      this.user = { ...this.populateWith }
      this.edit = true
    }
  },

  computed: {
    inCreationMode() {
      return !this.edit
    },

    inEditMode() {
      return this.edit
    },

    submitText() {
      return this.inCreationMode ? 'Create' : 'Edit'
    },

    nameIsEmpty() {
      return this.user.name === ''
    },

    canSubmit() {
      return !this.nameIsEmpty && this.usernameAvailable
    },

    inputIsCurrentUsername() {
      return this.user.name === this.populateWith['name']
    },

    username: {
      get() {
        return this.user.name
      },

      set(value) {
        this.user.name = value
        http
          .get('/users/available', { params: { name: value } })
          .then(({ data }) => {
            this.usernameAvailable = data.available
          })
      },
    },
  },

  methods: {
    onSubmit() {
      if (this.canSubmit) {
        this.$emit('submit:user', this.user)
        console.log('emit submit one user')
        this.clearForm()
        this.close()
      }
    },

    clearForm() {
      this.user = {
        id: null,
        name: '',
        posts: [],
      }
      this.edit = false
    },

    close() {
      this.$emit('close')
    },
  },
}
</script>

<style></style>
